### ISSUE TITLE
データベーステーブルリスト

### ISSUE THREAD

**Issue by g016c1123** [yuuuni1211/neec-gp#2]
**追加してほしいテーブルがあればコメントで教えてください。**

1.User_Table
-------------------------------------------------
create table student_profiles
(student_id char(9) unique not null,
name varchar(50) not null,
"create-at" date not null,
"update-at" date not null,
college_id integer not null,
primary key (student_id));
-------------------------------------------------

2.College_Table
-------------------------------------------------
create table college
(college_id integer not null,
college_name varchar(50) not null,
primary key (college_id));
-------------------------------------------------

3.Time_Table
-------------------------------------------------
create table time_table
(id_num integer not null,
time_id integer unique not null,
kamoku_id integer not null,
primary key (time_id));
-------------------------------------------------

4.Kamoku_Table
-------------------------------------------------
create table kamoku_table
(id_num integer not null,
kamoku_id integer unique not null,
primary key (kamoku_id));
-------------------------------------------------

5.Syukketsu_Table
-------------------------------------------------
create table syukketsu
(uketsuke_num integer unique not null,
date date not null,
time time not null,
student_id char(9) not null,
student_name varchar(50) not null,
time_id integer,
syukketsu_id integer,
primary key (uketsuke_num));
-------------------------------------------------

**Comment by yuuuni1211** [comment]
科目のテーブルの追加
生徒情報、ログイン情報は別のDBを作成して格納したほうが良きと思います。

**Comment by g016c1123** [comment]
修正しました。

**Comment by yuuuni1211** [comment]
ctsDBの出欠テーブルに、外部キーとして、kamoku_numを追加しないと、不整合が出ると思います。

**Comment by g016c1123** [comment]
データベーステーブル変更しました。
